### ISSUE TITLE
exampleのsave-to-webm は同一のhostから送信すると接続に失敗する

### ISSUE THREAD

**Issue by tetsu-koba** [hakobera/go-ayame#10]
exampleの save-to-webm でayame-lite につないで録画を試したのですが、何度やっても接続に失敗するので困っていました。同じ環境で、ayameのjavascript SDKのサンプルのrecvonlyでは受信ができているのでネットワークの問題ではなさそうです。

いろいろ試しているうちにダメなケースがわかりました。
webのsendonlyのページを開いているhostと、save-to-webmコマンドを実行するhostが同一だと接続に失敗します。同じネットワーク上のちがうhostから送信すると問題なく動作しました。
verbose オプションをつけて実行したときのログを採取したので貼っておきます。

同一hostから送信して接続に失敗したときのログ
[log_ng.txt](https://github.com/hakobera/go-ayame/files/4534971/log_ng.txt)

ちがうhostから送信して正常に動作したときのログ
[log_ok.txt](https://github.com/hakobera/go-ayame/files/4534972/log_ok.txt)

この挙動はあらかじめわかっていれば回避できるので、README.md に書いておくだけでもよいと思います。

**Comment by hakobera** [comment]
報告ありがとうございます。
再現条件がわかったので、調べてみます。

取り急ぎ、README に記載しておきます。

**Comment by hakobera** [comment]
私の環境では再現できなかったので、問題が起こる可能性がある、という趣旨で README に追記します。
